version: "3"

services:
  speedtest:
    image: miguelndecarvalho/speedtest-exporter:latest
    restart: unless-stopped
    network_mode: service:tailscale

  tailscale:
    image: tailscale/tailscale
    restart: unless-stopped
    environment:
      TS_EXTRA_ARGS: --login-server=${TAILSCALE_SERVER}
      TS_HOSTNAME: ${TAILSCALE_HOSTNAME}
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TS_STATE_DIR: "/var/lib/tailscale"
    volumes:
      - ${VOLUME_PATH}tailscale:/var/lib/tailscale


